### PR TITLE
Updated dependancies to be less specific and fixed unit tests

### PR DESCRIPTION
**Pull request by adamlc**
Although I've not actually tested it, I've made the composer requirements to be less specific so this package can be used in newer versions of Laravel.

Also fixed the unit tests

### CODE REVIEW

**Comment by fideloper** [comment]
Don't use this library :D

**Comment by fideloper** [comment]
I think Symfony's HTTP abstraction takes care of 99% of this and I just didn't know it. I was just learning about this stuff while writing it.

**Comment by adamlc** [comment]
@fideloper fair enough. How would you achieve the same thing now?

**Comment by fideloper** [comment]
Symfony's classes have all this stuff, I'd take a look there.
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1461
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L1074

(Your app needs to generate an eTag no matter what, but these classes have
the methods to do the other work for you - settings headers, comparing
request/response, etc)

**Comment by fideloper** [comment]
The real answer is "it's been so long since I looked, I don't remember 100%"

**Comment by adamlc** [comment]
Thanks :D

I'll take a look :)

**Comment by adamlc** [comment]
Just a quick update for anyone else interested. This is pretty easy now.

Assuming your Resource follows the same interface and your using Laravel...

``` php
//Create a new response and set last modified and etags
$response = Response::json();
$response->setLastModified($resource->getLastUpdated());
$response->setEtag($resource->getEtag());

//Check if the item has been modified. If not return a 304
if ($response->isNotModified(Request::instance())) {
    return Response::json(null, 304);
}

//Item has been modified. Continue..
$response->setData(
    [
        'hello' => 'world'
    ]
);

return $response;
```

**Comment by fideloper** [comment]
:+1:

**Pull request closed without merging**
